import Head from "next/head";
import Image from "next/image";

import Check from "../components/icons/Check";
import ArrowRight from "../components/icons/ArrowRight";

import heroImage from "../public/images/Amadu Kamara.jpg";
import amkam from "../public/images/Amkam.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-16">
        {/* Hero Setction */}
        <section className="flex my-12">
          <div className="w-1/2 pt-10">
            <h4 className="logo-text text-2xl">Hello!</h4>
            <h1 className="font-semibold h-text-color text-7xl my-2">
              I'm Amadu Kamara
            </h1>
            <ul className="mt-5">
              <li className="flex items-center mb-5 text-xl">
                <div className="bg-gray-100 h-text-color rounded-full p-2 mr-4 text-2xl">
                  <Check />
                </div>
                <span className="text-2xl">Frontend Developer</span>
              </li>
              <li className="flex items-center mb-5 text-xl">
                <div className="bg-gray-100 h-text-color rounded-full p-2 mr-4 text-2xl">
                  <Check />
                </div>
                <span className="text-2xl">Web designer</span>
              </li>
              <li className="flex items-center mb-5 text-xl">
                <div className="bg-gray-100 h-text-color rounded-full p-2 mr-4 text-2xl">
                  <Check />
                </div>
                <span className="text-2xl">UI/UX designer</span>
              </li>
              <li className="flex items-center mb-5 text-xl">
                <div className="bg-gray-100 h-text-color rounded-full p-2 mr-4 text-2xl">
                  <Check />
                </div>
                <span className="text-2xl">Frontend Developer</span>
              </li>
              <li className="flex items-center mb-5 text-xl">
                <div className="bg-gray-100 h-text-color rounded-full p-2 mr-4 text-2xl">
                  <Check />
                </div>
                <span className="text-2xl">
                  I teach students how to design and develop websites and
                  applications
                </span>
              </li>
            </ul>
            <button
              type="button"
              className="bg-btn py-5 px-12 text-xl rounded-md text-white my-6"
            >
              Get in Touch
            </button>
          </div>
          <div className="w-1/2 flex justify-center items-center">
            <Image
              src={heroImage}
              alt="Amadu Kamara"
              className="rounded-full shadow-md"
              width={480}
              height={480}
            />
          </div>
        </section>

        {/* About Section */}
        <section className="mt-24">
          <div className="flex justify-start items-center">
            <div className="w-1/5">
              <h1 className="text-5xl font-semibold">About Me</h1>
            </div>
            <div
              style={{
                border: "1px solid #0f9fc0",
                width: "100%",
                marginRight: "115px",
              }}
              className="w-4/5 hidden sm:block"
            ></div>
          </div>

          {/* About Amadu Kamara (Amkam) */}
          <div className="flex mt-4">
            <div className="w-3/5 mr-16">
              <p className="leading-loose text-justify text-lg">
                Hello! My name is Amadu Kamara, commonly known as Samuel Amkam,
                I enjoy creating things and making businesses, organizations,
                etc.. present on the internet. My interest in web development
                started back in 2017 when I first started hacking into Amazon's
                website, the website I admire the most — the hacking later turns
                out very interesting for me and it taught me a lot more about
                HTML & CSS!
              </p>
              <p className="mt-2 leading-loose text-justify text-lg">
                Fast-forward to today, and I've had the privilege of working at
                a software development company - a huge corporation, and an
                in-person web design and development Bootcamp in my incubator.
                My main focus these days is designing website, building web
                application, freelancing and teaching students how to design and
                develop a professional website.
              </p>
              <div className="mt-8 font-semibold tracking-wider">
                <h3 className="text-3xl">
                  Here are few of my stacks I've been working with recently:
                </h3>
              </div>
            </div>
            <div className="w-2/5 mr-32 bg-image pr-6 pb-4 rounded-md shadow-2xl bg-image">
              <Image
                src={amkam}
                alt="Samuel Amkam"
                className="shadow-2xl rounded-md"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
